package networking;

public enum Error {
	INVALID_COMMAND, INVALID_PARAMETER,
    NAME_INVALID, NAME_USED,
    QUEUE_INVALID,
    MOVE_TILES_UNOWNED, MOVE_INVALID,
    DECK_EMPTY, TRADE_FIRST_TURN,
    INVALID_CHANNEL,
    CHALLENGE_SELF, ILLEGAL_STATE, NOT_CHALLENGED
}
